services:
  web_legacy:
    build: .
    container_name: Inmunolife
    restart: always
    # MUY IMPORTANTE: Esto permite que el contenedor use la red de tu servidor.
    # Como tu settings.py apunta a 'localhost' para MySQL, esto hace que
    # el contenedor encuentre el MySQL que está instalado en tu VPS.
    network_mode: "host"

    volumes:
      # 1. Mapea el código de tu proyecto al contenedor
      - .:/app

      # 2. Mapea los estáticos según tu settings.py (STATIC_ROOT apunta un nivel arriba del BASE_DIR)
      - /opt/inmunovenv/Inmunolife/Inmunolife/static:/static
