# Generated by Django 4.2.16 on 2025-02-19 03:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname_contact', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email_contact', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_contact', models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)], verbose_name='Telefono')),
                ('topic_contact', models.TextField(null=True, verbose_name='Tema de elección')),
                ('comments_contact', models.TextField(null=True, verbose_name='Comentarios')),
                ('date_contact', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('status_contact', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Contactos',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contact',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=25, verbose_name='Primer apellido')),
                ('second_lastname', models.CharField(blank=True, max_length=20, verbose_name='Segundo apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('passrd', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('cellphone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Número de celular')),
                ('user_active', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('user_admin', models.BooleanField(default=False, verbose_name='Usuario admin')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('contenido', models.TextField(null=True, verbose_name='Contenido del post')),
                ('imagen', models.ImageField(null=True, upload_to='post/%Y/%M/%D', verbose_name='Imagen del post')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contactos')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['id'],
            },
        ),
    ]
