# Generated by Django 4.2.16 on 2025-02-13 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname_contact', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email_contact', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_contact', models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)], verbose_name='Telefono')),
                ('topic_contact', models.IntegerField(choices=[[0, 'Mas sobre las membresias'], [1, 'Cotizar'], [2, 'Dudas sobre pagos'], [3, 'Dudas en general y sugerencias']], null=True, verbose_name='Tema de elección')),
                ('comments_contact', models.TextField(null=True, verbose_name='Comentarios')),
                ('date_contact', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('status_contact', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Contactos',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contact',
                'ordering': ['id'],
            },
        ),
    ]
