# Generated by Django 4.2.16 on 2025-02-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactos',
            old_name='comentarios',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='fecha_alta',
            new_name='high_date',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='apellido',
            new_name='lastname_contac',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='nombre',
            new_name='namecontac',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='estado',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='contactos',
            name='telefono',
        ),
        migrations.AddField(
            model_name='contactos',
            name='phone_contac',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Telefono'),
        ),
    ]
