# Generated by Django 4.2.16 on 2025-02-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default='Pepe', max_length=20, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
