# Generated by Django 4.2.16 on 2025-02-18 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='phone_contact',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Telefono'),
        ),
    ]
