# Generated by Django 4.2.16 on 2025-02-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='comments_contact',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='email_contact',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
