# Generated by Django 4.2.16 on 2025-02-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='laststname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passrd',
        ),
    ]
