# Generated by Django 4.2.16 on 2025-02-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_comentarios_contactos_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='lastname_contac',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='namecontac',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
