# Generated by Django 4.2.16 on 2025-02-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactos_comments_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='passrd',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
    ]
