# Generated by Django 4.2.16 on 2025-02-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactos_phone_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='phone_contact',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
    ]
