# Generated by Django 4.2.16 on 2025-03-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_register_passrd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='topic_contact',
            field=models.CharField(choices=[('Mas sobre las membresias', 'Mas sobre las membresias'), ('Cotizar', 'Cotizar'), ('Dudas sobre pagos', 'Dudas sobre pagos'), ('Dudas en general y sugerencias', 'Dudas en general y sugerencias')], max_length=50, null=True, verbose_name='Tema de elección'),
        ),
    ]
