# Generated by Django 4.2.16 on 2025-02-10 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactos_lastname_contac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='phone_contac',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
