# Generated by Django 4.2.16 on 2025-02-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contactos_phone_contac_alter_contactos_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactos',
            old_name='comments',
            new_name='comments_contact',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='high_date',
            new_name='date_contact',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='email',
            new_name='email_contact',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='lastname_contac',
            new_name='lastname_contact',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='namecontac',
            new_name='name_contact',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='phone_contac',
            new_name='phone_contact',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='status',
            new_name='status_contact',
        ),
    ]
