# Generated by Django 4.2.16 on 2025-03-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contactos_topic_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Token de restablecimiento'),
        ),
    ]
