# Generated by Django 4.2.16 on 2025-02-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_comments_contactos_comments_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='topic_contact',
            field=models.TextField(null=True, verbose_name='Tema de elección'),
        ),
    ]
