# Generated by Django 4.2.16 on 2025-03-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_register_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de restablecimiento'),
        ),
    ]
