# Generated by Django 4.2.16 on 2025-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_register_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración del token'),
        ),
    ]
