# Generated by Django 4.2.16 on 2025-03-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_register_reset_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
