# Generated by Django 4.2.16 on 2025-03-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactos_visto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactos',
            old_name='visto',
            new_name='seen_contact',
        ),
    ]
