# Generated by Django 4.2.16 on 2025-03-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_visto_contactos_seen_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['id'], 'verbose_name': 'Usuario Protego', 'verbose_name_plural': 'Usuarios Protego'},
        ),
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
